# https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md
# https://docs.microsoft.com/de-de/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019
# escape=`

FROM wmcdevhub.azurecr.io/git-sdk:latest

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Set up environment to collect install errors.
COPY Install.cmd C:\TEMP\
ADD https://aka.ms/vscollect.exe C:\TEMP\collect.exe

RUN C:\TEMP\Install.cmd C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
 --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended`
 --add Microsoft.VisualStudio.Component.VC.ATLMFC`
 --add Microsoft.VisualStudio.Component.VC.v141.x86.x64`
 --add Microsoft.Component.MSBuild `
 --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
 --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
 --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
 --remove Microsoft.VisualStudio.Component.Windows81SDK `
 --installPath C:\BuildTools


RUN C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat && set > vars.txt
RUN for /F "tokens=1,* delims== " %a in (vars.txt) do powershell -Command Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name '%a' -Value '%b'  

# Define the entry point for the docker container.
# This entry point starts the developer command prompt and launches the PowerShell shell.
# ENTRYPOINT ["C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", "&&", "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
